#!/usr/bin/env bash
# loki-changelog.sh — regenerate loki/CHANGELOG.md from the Loki logs
#
# The CHANGELOG is a VIEW OVER the log, not a separate source of record. It reads
# every loki/logs/*.md (all months), selects each `## [applied]` finding that
# carries a `- **Pinned-by:**` ref, and (re)writes loki/CHANGELOG.md from scratch.
# Because it fully regenerates each run it is idempotent and dedup is free: an
# applied finding that later regresses (loses its Pinned-by / flips status) simply
# stops appearing. Never hand-edit CHANGELOG.md — edit the log and rerun this.
#
# Backfill guard: any `## [applied]` finding that LACKS a Pinned-by line is NOT
# silently promoted or dropped — it is printed as "needs triage" so a human can
# backfill a Pinned-by ref or reclassify the finding.
#
# Usage:
#   loki-changelog.sh            regenerate loki/CHANGELOG.md + print triage report
#   loki-changelog.sh --check    dry-run: print the triage report only, write nothing
#
# READ-ONLY on the logs; only writes loki/CHANGELOG.md.

set -uo pipefail

CHECK_ONLY=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) CHECK_ONLY=1; shift ;;
        *) shift ;;
    esac
done

# Resolve the repo root from this script's real location (it is symlinked into
# ~/.syndicate/scripts/, so follow the link back to the repo).
SOURCE="${BASH_SOURCE[0]}"
if command -v readlink >/dev/null 2>&1; then
    SOURCE="$(readlink -f "$SOURCE" 2>/dev/null || echo "$SOURCE")"
fi
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOGS_DIR="$REPO_ROOT/loki/logs"
CHANGELOG="$REPO_ROOT/loki/CHANGELOG.md"

if [ ! -d "$LOGS_DIR" ]; then
    echo "loki-changelog: no logs dir at $LOGS_DIR" >&2
    exit 1
fi

# Gather log files in a deterministic order.
logfiles=()
while IFS= read -r f; do
    logfiles+=("$f")
done < <(find "$LOGS_DIR" -maxdepth 1 -type f -name '*.md' | LC_ALL=C sort)

if [ "${#logfiles[@]}" -eq 0 ]; then
    echo "loki-changelog: no log files (*.md) in $LOGS_DIR" >&2
    exit 1
fi

# Parse every finding block. A block runs from a `## ` header to the next one.
# Rows are the changelog-eligible entries; triage are applied-without-pinned-by.
rows=()
triage=()

cur_status=""; cur_title=""; cur_when=""; cur_action=""; cur_pinned=""

flush_block() {
    [ "$cur_status" = "applied" ] || return 0
    if [ -n "$cur_pinned" ]; then
        # when \t title \t fix \t pinned-by
        rows+=("${cur_when}"$'\t'"${cur_title}"$'\t'"${cur_action}"$'\t'"${cur_pinned}")
    else
        triage+=("${cur_when}"$'\t'"${cur_title}")
    fi
}

while IFS= read -r line; do
    if [[ "$line" =~ ^##[[:space:]]\[([^]]*)\][[:space:]](.*)$ ]]; then
        flush_block
        cur_status="${BASH_REMATCH[1]}"
        cur_title="${BASH_REMATCH[2]}"
        cur_when=""; cur_action=""; cur_pinned=""
    elif [[ "$line" =~ ^##[[:space:]] ]]; then
        # a `## ` header that isn't a `[status]` finding (e.g. MONTH REVIEW) — reset.
        flush_block
        cur_status=""; cur_title=""; cur_when=""; cur_action=""; cur_pinned=""
    elif [[ "$line" =~ ^-[[:space:]]\*\*When:\*\*[[:space:]](.*)$ ]]; then
        cur_when="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^-[[:space:]]\*\*Action[[:space:]]taken:\*\*[[:space:]](.*)$ ]]; then
        cur_action="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^-[[:space:]]\*\*Pinned-by:\*\*[[:space:]](.*)$ ]]; then
        cur_pinned="${BASH_REMATCH[1]}"
    fi
done < <(cat -- "${logfiles[@]}")
flush_block

# --- Backfill / triage dry-run report (always printed) --------------------------
if [ "${#triage[@]}" -gt 0 ]; then
    echo "loki-changelog: ${#triage[@]} [applied] finding(s) LACK a Pinned-by line — needs triage:"
    echo "  (backfill Pinned-by or reclassify; these will NOT appear in CHANGELOG.md until pinned)"
    while IFS= read -r t; do
        IFS=$'\t' read -r t_when t_title <<< "$t"
        echo "  - [${t_when:-no-when}] ${t_title}"
    done < <(printf '%s\n' "${triage[@]}" | LC_ALL=C sort)
else
    echo "loki-changelog: no un-pinned [applied] findings — nothing to triage."
fi

if [ "$CHECK_ONLY" -eq 1 ]; then
    echo "loki-changelog: --check (dry-run) — CHANGELOG.md not written."
    exit 0
fi

# --- Regenerate CHANGELOG.md from scratch (deterministic) ------------------------
{
    echo "# Loki Defect CHANGELOG"
    echo ""
    echo "> GENERATED by scripts/loki-changelog.sh — do not hand-edit."
    echo "> A regenerable VIEW over loki/logs/*.md: every \`[applied]\` finding that"
    echo "> carries a \`Pinned-by\` ref. Rerun the script after any log status change;"
    echo "> it rewrites this file from scratch (an applied finding that regresses and"
    echo "> loses its Pinned-by simply drops out)."
    echo ""
    echo "| Defect | Fix | Pinned-by | When |"
    echo "|--------|-----|-----------|------|"
    if [ "${#rows[@]}" -gt 0 ]; then
        printf '%s\n' "${rows[@]}" | LC_ALL=C sort | while IFS=$'\t' read -r r_when r_title r_fix r_pinned; do
            # Escape pipes so cell text can't break the markdown table.
            r_title="${r_title//|/\\|}"
            r_fix="${r_fix//|/\\|}"
            r_pinned="${r_pinned//|/\\|}"
            [ -n "$r_fix" ] || r_fix="—"
            printf '| %s | %s | %s | %s |\n' "$r_title" "$r_fix" "$r_pinned" "$r_when"
        done
    fi
} > "$CHANGELOG"

echo "loki-changelog: wrote ${#rows[@]} row(s) → ${CHANGELOG}"
