#!/usr/bin/env bash
# Write evidence packet — records what a pipeline did
#
# Called by Odin/Ledger at the end of each pipeline.
# Creates a structured record at ~/.syndicate/evidence/YYYY-MM-DD/
#
# Usage: ./scripts/write-evidence-packet.sh \
#          --trigger "user prompt" \
#          --pipeline "Scribe → Forge → Athena → Hermes" \
#          --outcome "MR opened" \
#          --branch "fix/123-thing" \
#          --mr "147" \
#          --files "path/to/file.py" \
#          --duration "4m"

set -euo pipefail

EVIDENCE_DIR="${HOME}/.syndicate/evidence/$(date +%Y-%m-%d)"
mkdir -p "$EVIDENCE_DIR"

# Parse arguments
TRIGGER=""
PIPELINE=""
OUTCOME=""
BRANCH=""
MR=""
FILES=""
DURATION=""
CONCERNS=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --trigger) TRIGGER="$2"; shift 2 ;;
        --pipeline) PIPELINE="$2"; shift 2 ;;
        --outcome) OUTCOME="$2"; shift 2 ;;
        --branch) BRANCH="$2"; shift 2 ;;
        --mr) MR="$2"; shift 2 ;;
        --files) FILES="$2"; shift 2 ;;
        --duration) DURATION="$2"; shift 2 ;;
        --concerns) CONCERNS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# Generate timestamp-based ID
PACKET_ID="$(date +%H%M%S)-$(( RANDOM % 1000 ))"
PACKET_FILE="${EVIDENCE_DIR}/${PACKET_ID}.md"

cat > "$PACKET_FILE" << EOF
# Evidence Packet: ${PACKET_ID}

**Timestamp:** $(date -Iseconds)
**Triggered by:** ${TRIGGER:-"(not recorded)"}
**Pipeline:** ${PIPELINE:-"(not recorded)"}

## Outcome
${OUTCOME:-"(not recorded)"}

## Details
- **Branch:** ${BRANCH:-"n/a"}
- **MR/PR:** ${MR:-"n/a"}
- **Files:** ${FILES:-"n/a"}
- **Duration:** ${DURATION:-"n/a"}

## Concerns Raised
${CONCERNS:-"None"}

---
*Generated by Syndicate pipeline engine*
EOF

echo "$PACKET_FILE"
